NIAEFEUP/uni

app_feup/lib/main.dart

Lock screen rotation to always be in portrait. Fix issue #30

Lock screen rotation

---

app_feup/lib/controller/parsers/parser-schedule.dart
app_feup/lib/redux/actionCreators.dart

Replaced HTML parser with Sigarra's endpoint. ScheduleWidget now uses the schedule from the logged in account. Fix #31

Schedule Endpoint

---

app_feup/lib/view/widgets/ScheduleCard.dart
app_feup/lib/view/widgets/ScheduleEventRectangle.dart
app_feup/lib/view/widgets/ScheduleRow.dart

Add class type to Schedule card. Fix #39

Add class type to ScheduleCard

---

app_feup/lib/redux/actionCreators.dart

Fix #54 . Everytime the store is now accessed, it is first check if session content has been initalized or not

Fixed Null session Exception

---

app_feup/lib/view/Pages/ExamsPageView.dart

Fix #53 . Last exam is now being properly displayed

Last Exam is now showing

---

app_feup/lib/controller/loadinfo.dart
app_feup/lib/redux/actionCreators.dart

Fixed error when session would call store when session information hadn't been loaded yet.

Fixed session error

---

app_feup/lib/main.dart
app_feup/lib/view/Pages/AboutPageView.dart
app_feup/lib/view/widgets/NavigationDrawer.dart

Added a view card for the about page, that contains the NI logo and an app description (to be changed). Fix #59

Added an about page (text not final)

---

app_feup/lib/view/Pages/ExamsPageView.dart
app_feup/pubspec.yaml

Fix an newly found issue when there is only one exam.

Fixed bug when there was only one exam

---

app_feup/android/local.properties
app_feup/lib/view/Widgets/ExamCard.dart
app_feup/lib/view/Widgets/ScheduleCard.dart

Fixed bug where screen went all black whenever going back.
This was due to the fact that navigator was misleadingly pushing a replacement, making so that navigator did not build a stack of its routes.

Changed navigator to push to stack

---

app_feup/lib/Main.dart

Now settings being passed to page routes

Added settings to routes

---

app_feup/.gitignore
app_feup/ios/Runner/GeneratedPluginRegistrant.h
app_feup/ios/Runner/GeneratedPluginRegistrant.m
app_feup/lib/controller/LoadInfo.dart
app_feup/lib/controller/Logout.dart
app_feup/lib/controller/local_storage/AppLastUpdateDatabase.dart
app_feup/lib/controller/local_storage/AppLastUserInfoUpdateDatabase.dart
app_feup/lib/model/AppState.dart
app_feup/lib/model/SchedulePageModel.dart
app_feup/lib/redux/ActionCreators.dart
app_feup/lib/redux/Actions.dart
app_feup/lib/redux/Reducers.dart
app_feup/lib/view/Pages/SchedulePageView.dart
app_feup/lib/view/Widgets/ExamCard.dart
app_feup/lib/view/Widgets/GenericCard.dart
app_feup/lib/view/Widgets/RequestDependentWidgetBuilder.dart
app_feup/lib/view/Widgets/ScheduleCard.dart

Changed all AppStates to have non-dynamic lists (fixes #162 ). Switched a store provider for a store connector in order to make it so that page rebuilds whenever information is stored.

Fixed Loading Schedule Page

---

app_feup/lib/redux/ActionCreators.dart
app_feup/lib/redux/Reducers.dart
app_feup/lib/view/Pages/ExamsPageView.dart
app_feup/lib/view/Pages/SchedulePageView.dart
app_feup/lib/view/Widgets/ExamCard.dart
app_feup/lib/view/Widgets/RequestDependentWidgetBuilder.dart
app_feup/lib/view/Widgets/ScheduleCard.dart

Cards now display information even when there's on internet on start. Fixes #168

Fix Card when No internet

---

app_feup/lib/utils/Constants.dart
app_feup/lib/view/Pages/ExamsPageView.dart
app_feup/lib/view/Pages/SchedulePageView.dart
app_feup/lib/view/Widgets/BackButtonExitWrapper.dart
app_feup/lib/view/Widgets/BugReportForm.dart
app_feup/lib/view/Widgets/ExamCard.dart
app_feup/lib/view/Widgets/GenericCard.dart
app_feup/lib/view/Widgets/MainCardsList.dart
app_feup/lib/view/Widgets/RequestDependentWidgetBuilder.dart
app_feup/lib/view/Widgets/ScheduleCard.dart

Translated every viewable English string to Portuguese

Translate to Portuguese

---

app_feup/lib/controller/parsers/ParserExams.dart
app_feup/lib/controller/parsers/ParserSchedule.dart
app_feup/lib/view/Pages/ExamsPageView.dart
app_feup/lib/view/Widgets/ExamCard.dart
app_feup/lib/view/Widgets/ScheduleEventRectangle.dart
app_feup/lib/view/Widgets/ScheduleRow.dart

Adding season information to exam items (both in the card and in the exam page). Also added a message when there are no rooms.

Fixed missing rooms and added exam season

---

app_feup/lib/model/ProfilePageModel.dart
app_feup/lib/view/Pages/ProfilePageView.dart

Fix #196 . Also fixes bug where personal photo does not show on profile page

Unnamed Profile Page

---

app_feup/lib/Main.dart
app_feup/lib/view/Widgets/BusStopSearch.dart
app_feup/lib/view/Widgets/TripRow.dart

Added a minute indicator (') to time remaining until bus arrival and improved button design in "add bus stop" dialog

Stops UX improvements

---

app_feup/lib/view/Pages/LoginPageView.dart

Trim to login form must have been lost in any merge or rebase. This PR is to add this back before launch.

Added trim to login form strings

---

.github/pull_request_template.md

This allows for having explicit steps in every PR without much effort and ensuring proper reviews

Created PR template for easier and complete reviews

---

app_feup/lib/model/app_state.dart
app_feup/lib/view/Pages/general_page_view.dart
app_feup/lib/view/Pages/login_page_view.dart
app_feup/lib/view/Widgets/main_cards_list.dart

Closes #222.
Added a condition to check if the user is authenticated before navigating to main page.

Fix empty home page after signing out

---

app_feup/lib/model/entities/exam.dart
app_feup/lib/redux/action_creators.dart
app_feup/pubspec.yaml
app_feup/test/unit/redux/exam_action_creators_test.dart

Before this pull request exams disapeared at 00:00 on the day of the exam.
This pull request fixes this issue, only deleting the exam after it is finished.
Closes #292

Exam disappearing in Exam Day

---

app_feup/lib/model/entities/time_utilities.dart
app_feup/lib/view/Widgets/generic_card.dart
app_feup/lib/view/Widgets/schedule_card.dart
app_feup/pubspec.yaml

Closes #259 
Changed the time format (hours/minutes) in generic_card.dart (issue 250/259), e.g., having 00:00, instead of 0:0.

Update refresh time format (hours/minutes)

---

app_feup/lib/view/Pages/login_page_view.dart
app_feup/pubspec.yaml

I could not reproduce #332, so please let me know if this fixes it.

Restore username login text keyboard

---

app_feup/lib/view/Pages/schedule_page_view.dart
app_feup/pubspec.yaml

Closes #173
Schedule page can no longer be scrollable unless it actually has more content that can fit in the page.

Fixed schedule being scrollable when it shouldn't

---

app_feup/lib/main.dart
app_feup/lib/view/Widgets/page_transition.dart
app_feup/pubspec.yaml

Closes #245 
Remove sliding animation when switching pages and replaced it with a subtler fading animation.

Added page transition animation for main menu

---

.github/pull_request_template.md
app_feup/README.md
app_feup/pubspec.yaml
changelog.md

- Adds changelog and its expected behavior in PR template
- Bumps minor version to 1.1.0

Minor version 1.1 and introduction of changelog.md

---

app_feup/ios/Flutter/Debug.xcconfig
app_feup/ios/Flutter/Release.xcconfig
app_feup/ios/Podfile
app_feup/ios/Podfile.lock
app_feup/ios/Runner.xcodeproj/project.pbxproj
app_feup/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
app_feup/ios/Runner.xcworkspace/contents.xcworkspacedata

Files related to cocoaPods were added.
App is running without errors.

Add ios specific files

---

app_feup/lib/view/Widgets/link_button.dart

This line fixes the font size of links card.
-   [ ] Properly mentions the change in `whatsnew/whatsnew-pt-PT`

Fix links font size

---

.dockerignore
.github/dependabot.yaml
.github/workflows/deploy.yaml
docker-compose.yml
uni/lib/controller/load_static/terms_and_conditions.dart

-   [ ] Properly mentions the change in `whatsnew/whatsnew-pt-PT`

Remove remaining app_feup references

---

uni/lib/controller/local_storage/app_restaurant_database.dart

Fix database locked out for 10s error, when saving restauraunts
Closes #471
-   [X] Terms and conditions reflect the current change
-   [X] Increments version in `pubspec.yaml` (changes `1.0.0+1` to `1.0.0+2` for example)
-   [X] Properly mentions the change in `whatsnew/whatsnew-pt-PT`
-   [X] Properly adds entry in `changelog.md` with the change

Fix database locked out for 10s

---

.github/pull_request_template.md
.github/workflows/deploy.yaml
whatsnew/whatsnew-pt-PT

Closes #534 
-   [ ] Properly mentions the change in `whatsnew/whatsnew-pt-PT`

Refer whatsnew dir for beta deploys

---

uni/lib/controller/fetchers/all_course_units_fetcher.dart
uni/lib/controller/parsers/parser_course_units.dart
uni/lib/model/entities/course_unit.dart

Fix parser status; ditch invalid course units

---

uni/lib/view/Widgets/faculty_maps/faculty_maps.dart
uni/lib/view/Widgets/floorless_location_marker_popup.dart
uni/lib/view/Widgets/location_marker.dart
uni/lib/view/Widgets/location_marker_popup.dart

Closes #559
Uses Theme(context).brightness to check if theme is dark or light
-   [x] If aimed at production, writes new summary in `whatsnew/whatsnew-pt-PT`
-   [x] Properly adds entry in `changelog.md` with the change
-   [x] Clean, well structured code

Fix system theme bug on locations

---

uni/lib/view/Pages/login_page_view.dart
uni/lib/view/Widgets/back_button_exit_wrapper.dart
uni/lib/view/Widgets/bus_stop_search.dart
uni/lib/view/Widgets/create_print_mb_dialog.dart
uni/lib/view/Widgets/exam_filter_form.dart
uni/lib/view/Widgets/main_cards_list.dart
uni/lib/view/Widgets/schedule_slot.dart
uni/lib/view/Widgets/terms_and_condition_dialog.dart
uni/lib/view/theme.dart

Fixing some litle dark theme bugs
Before / After
<div>
</div>
Before / After
<div>
</div>
Before / After
<div>
</div>
Before / After
<div>
</div>

fixing alertDialog buttons text color, bodyTexts and schedule title

---

.github/workflows/deploy.yaml

Propagate version bump from master to develop

---

.github/workflows/deploy.yaml

Fix minor version bump and commit propagation

---

.github/workflows/test_lint.yaml
Dockerfile
uni/lib/view/login/widgets/faculties_selection_form.dart
uni/lib/view/login/widgets/inputs.dart
uni/pubspec.yaml

Upgraded flutter version from 3.0.5 to 3.3.2

Migrate app to Flutter 3.3

---

uni/lib/model/entities/exam.dart
uni/lib/view/exams/exams.dart

Fix bug: exams displaying the weekday instead of the month

---

uni/lib/controller/load_info.dart
uni/lib/controller/local_storage/app_restaurant_database.dart
uni/lib/model/entities/restaurant.dart
uni/lib/redux/action_creators.dart

Closes #688 
Restaurants are properly loaded from the database when there is no internet connection
-   [x] If aimed at production, writes new summary in `whatsnew/whatsnew-pt-PT`
-   [x] Properly adds entry in `changelog.md` with the change

Retrieve restaurants from database

---

.github/workflows/deploy.yaml

Fix push to develop command

---

.github/workflows/app_version_integrity.yaml
.github/workflows/deploy.yaml
.github/workflows/test_lint.yaml

Updating the checkout action plugin to remove the deprecated warning.

Use new checkout version

---

uni/lib/model/providers/exam_provider.dart

Exams appear sometimes not sorted

---

uni/lib/model/providers/state_provider_notifier.dart

Update update time only if successful

---

uni/android/app/build.gradle

Update master target sdk version

---

uni/lib/model/entities/lecture.dart

Schedule displaying wrong times

---

uni/lib/view/home/widgets/exit_app_dialog.dart
uni/lib/view/home/widgets/main_cards_list.dart
uni/lib/view/login/login.dart

Use home back button action on login page

---

uni/lib/view/home/widgets/schedule_card.dart

Refactor lecture card and show all upcoming classes from today

---

uni/lib/view/home/widgets/exam_card.dart

Exam card string error

---

uni/lib/model/entities/library_occupation.dart
uni/lib/view/library/library.dart

Closes #842 , Closes #970 
- Added limiter to maximum occupation percentage.
- Made subtitle visible on dark mode

Fixed library colors & max percentage

---

uni/lib/model/entities/course_units/course_unit.dart

Fixes https://niaefeup.sentry.io/issues/4528664543

Allow null course unit year

---

uni/lib/view/useful_info/widgets/sigarra_links_card.dart

Closes #969
Removed Calendar Link

[Fix][#969] Calendar Link Removed

---

.github/workflows/deploy.yaml

Because the deploy action changes the cwd kekw

Fix app_version and pubspec paths

---

.github/workflows/deploy.yaml

Make deploy workflow use github environment

---

.github/workflows/app_version_integrity.yaml
.github/workflows/deploy.yaml
.github/workflows/format_lint_test.yaml

This PR backports the deployment action changes from develop to master in order to hotfixes to work until the next release.

Cherry pick new deployment/versioning changes from develop

---

.github/workflows/deploy.yaml

Closes #1143 
This is a rough patch and not the final fix

Fix version code superseeding by eagerly deploying

---

.github/workflows/deploy.yaml

Cherry pick Deploy action changes from master to develop

---

uni/lib/utils/navbar_items.dart

Change restaurant icons to free_breakfast in bottom navbar

---

uni/pubspec.lock

This PR runs `flutter pub upgrade`.

build(deps): upgrade dependencies

---

uni/lib/view/common_widgets/pages_layouts/general/widgets/bottom_navigation_bar.dart

Fix bottom navbar padding

---

uni/lib/controller/local_storage/database/app_restaurant_database.dart

Closes #1173.
This PR changes the restaurant database so that insertion operations are awaited before the transaction is committed.

hotfix: closed transaction in restaurants database

---

uni/assets/text/TermsAndConditions.md

Updates the terms and conditions date. Previously, the terms and conditions said they were last updated in 2023, which is not correct.

docs: update terms and conditions date

---

.github/workflows/deploy.yaml
.github/workflows/format_lint_test.yaml
uni/android/app/build.gradle
uni/android/app/src/debug/AndroidManifest.xml
uni/android/app/src/main/AndroidManifest.xml
uni/android/app/src/profile/AndroidManifest.xml
uni/android/build.gradle
uni/android/gradle/wrapper/gradle-wrapper.properties
uni/android/settings.gradle
uni/lib/view/bug_report/widgets/form.dart
uni/lib/view/common_widgets/last_update_timestamp.dart
uni/lib/view/common_widgets/toast_message.dart
uni/lib/view/home/widgets/exit_app_dialog.dart
uni/lib/view/login/login.dart
uni/lib/view/profile/widgets/account_info_card.dart
uni/lib/view/profile/widgets/reference_section.dart
uni/pubspec.lock
uni/pubspec.yaml

Bump Flutter, Gradle dependencies to latest stable versions

---

uni/lib/model/utils/time/week.dart

This pull request cherrypicks a hotfix made to week in order to handle timezone changes.

chore: cherrypick `hotfix/make-week-handle-timezone-changes`

---

uni/android/app/build.gradle
uni/pubspec.yaml

Bump java overall version from 1.8 to 17 and ua_client_hints

bump java version and ua_client_hints

---

.github/workflows/deploy.yaml
.github/workflows/format_lint_test.yaml
uni/android/app/build.gradle
uni/android/app/proguard-rules.pro
uni/android/gradle/wrapper/gradle-wrapper.properties
uni/lib/view/common_widgets/generic_expansion_card.dart
uni/lib/view/common_widgets/pages_layouts/general/general.dart
uni/lib/view/common_widgets/pages_layouts/general/widgets/bottom_navigation_bar.dart
uni/lib/view/common_widgets/pages_layouts/general/widgets/top_navigation_bar.dart
uni/lib/view/common_widgets/pages_layouts/secondary/secondary.dart
uni/lib/view/home/widgets/main_cards_list.dart
uni/lib/view/home/widgets/remaining_exams_card.dart
uni/lib/view/locations/widgets/floorless_marker_popup.dart
uni/lib/view/locations/widgets/marker.dart
uni/lib/view/locations/widgets/marker_popup.dart
uni/lib/view/profile/widgets/create_print_mb_dialog.dart
uni/lib/view/theme.dart
uni/pubspec.lock
uni/pubspec.yaml

Just a maintenance PR to keep Flutter up-to-date.
I run `flutter build apk --debug` and `flutter build apk --release` locally, both pass (I used dummy `key.properties` for the release build).

Bump Flutter to 3.22

---

uni/lib/controller/local_storage/preferences_controller.dart
uni/pubspec.lock
uni/pubspec.yaml

Remove password encryption

---

uni/pubspec.lock
uni/pubspec.yaml

Closes #1264
Bumps `audio_session` version to the newest release.

Bump audio_session version

---

packages/uni_ui/lib/theme.dart

Setting up the theme

---

.github/workflows/deploy.yaml
README.md
packages/uni_app/pubspec.lock
packages/uni_app/pubspec.yaml
packages/uni_ui/lib/generic_card.dart
packages/uni_ui/lib/theme.dart
packages/uni_ui/pubspec.lock
packages/uni_ui/pubspec.yaml

Closes #1270 
Use this just like a `Container` or `Card`. It receives a child to place inside and additional properties you may choose to modify.

New Generic Card

---

packages/uni_ui/lib/modal/modal.dart
packages/uni_ui/lib/modal/widgets/enrollment_info.dart
packages/uni_ui/lib/modal/widgets/info_row.dart
packages/uni_ui/lib/modal/widgets/person_info.dart
packages/uni_ui/lib/modal/widgets/service_info.dart
packages/uni_ui/lib/theme.dart
packages/uni_ui/pubspec.lock
packages/uni_ui/pubspec.yaml

Closes #1296 
Modal Widget for the app's redesign.

Modal Widget

---

packages/uni_app/lib/controller/local_storage/database/app_exams_database.dart
packages/uni_app/lib/controller/local_storage/database/app_user_database.dart
packages/uni_app/lib/generated/model/entities/exam.g.dart
packages/uni_app/lib/model/entities/exam.dart
packages/uni_app/lib/model/providers/lazy/exam_provider.dart
packages/uni_app/lib/view/exams/exams.dart
packages/uni_app/lib/view/exams/widgets/exam_row.dart
packages/uni_app/lib/view/home/widgets/exam_card.dart
packages/uni_app/lib/view/home/widgets/next_exams_card.dart
packages/uni_app/lib/view/home/widgets/remaining_exams_card.dart
packages/uni_app/test/unit/view/Widgets/exam_row_test.dart

Closes #1175
- Removed SQLite reserved keywords from sql scripts;
- Updated the exam model to reflect this changes;
- Updated UI components that depend on the updated model;
- Added missing logic for database version update where needed;

fix: sqlite keywords

---

packages/uni_app/lib/session/logout/uni_logout_handler.dart

This PR adds a logout redirect URI to the logout process.

fix: add post logout url

---

packages/uni_app/lib/controller/local_storage/database/app_course_units_database.dart

Fix a null course unit id error

---

packages/uni_app/lib/view/schedule/schedule.dart

Add vertical scroll at lectures tab

---

packages/uni_app/lib/controller/fetchers/schedule_fetcher/schedule_fetcher_new_api.dart
packages/uni_app/lib/model/providers/lazy/lecture_provider.dart

Fixing duplicate classes

---

packages/uni_app/lib/main.dart
packages/uni_app/pubspec.lock
packages/uni_app/pubspec.yaml

In-app updates

---

packages/uni_app/lib/controller/local_storage/preferences_controller.dart
packages/uni_app/lib/view/course_units/course_units.dart

Save ucs page semester and school year dropdown values on preferences

---

packages/uni_app/lib/controller/parsers/parser_restaurants.dart

Fixing JSON casts

---

packages/uni_app/lib/controller/parsers/parser_restaurants.dart

Releases version 1.9.6.
Contains an important fix for the display of restaurant meals.

release: v1.9.6

---

packages/uni_app/README.md

fixed small error in the path for MVC.png

fixed path to MVC.png

---

packages/uni_app/android/app/build.gradle
packages/uni_app/android/app/src/debug/res/values/string.xml
packages/uni_app/android/app/src/main/AndroidManifest.xml
packages/uni_app/android/app/src/main/res/values/string.xml

Changed build.gradle to add the new suffix. Changed AndroidManifest.xml to change the app name based on release or debug version.

Diferentiate the release and debug versions of uni.

---

packages/uni_app/lib/main.dart
packages/uni_app/lib/utils/navigation_items.dart
packages/uni_app/lib/view/settings/settings.dart

Closes #1156
All fade transitions applied
-   [] Clean, well-structured code

Finish Transitions

---

packages/uni_app/lib/controller/local_storage/database/app_calendar_database.dart
packages/uni_app/lib/controller/local_storage/database/app_course_units_database.dart
packages/uni_app/lib/controller/local_storage/database/app_courses_database.dart
packages/uni_app/lib/controller/local_storage/database/app_lectures_database.dart
packages/uni_app/lib/controller/local_storage/database/app_library_occupation_database.dart
packages/uni_app/lib/controller/local_storage/database/app_references_database.dart

Closes  #1388
[Description of the changes proposed in the pull request. Include steps to replicate the behavior and screenshots if UI is updated]
-   [X] Terms and conditions reflect the current change
-   [X] Behavior is as expected
-   [X] Clean, well-structured code

database serialization

---

packages/uni_app/lib/main.dart

fix: light theme

---

packages/uni_app/lib/generated/intl/messages_en.dart
packages/uni_app/lib/generated/intl/messages_pt_PT.dart
packages/uni_app/lib/generated/l10n.dart
packages/uni_app/lib/l10n/intl_en.arb
packages/uni_app/lib/l10n/intl_pt_PT.arb
packages/uni_app/lib/view/restaurant/widgets/favorite_restaurants_button.dart

Fix restaurants favorite button

---

packages/uni_app/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml

Added support for android themed icons in the home screen.
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

Monochrome icon support for the new uni app icon.

---

packages/uni_app/lib/view/academic_path/exam_page.dart
packages/uni_app/lib/view/academic_path/widgets/no_exams_widget.dart

Center Exams Page onNullContent's Illustration

---

flake.lock
flake.nix
packages/uni_app/lib/controller/local_storage/preferences_controller.dart
packages/uni_app/lib/view/home/edit_home.dart
packages/uni_app/lib/view/home/widgets/edit/draggable_element.dart
packages/uni_app/lib/view/home/widgets/edit/draggable_square.dart
packages/uni_app/lib/view/home/widgets/edit/draggable_tile.dart
packages/uni_app/lib/view/home/widgets/edit/draggable_utils.dart

fix: dragging in homepage edit

---

packages/uni_app/lib/model/providers/startup/profile_provider.dart

Fix to some course details not appearing on app restart

---

packages/uni_app/lib/generated/intl/messages_pt_PT.dart
packages/uni_app/lib/l10n/intl_pt_PT.arb
packages/uni_app/lib/view/academic_path/widgets/no_classes_widget.dart
packages/uni_app/lib/view/home/widgets/schedule/schedule_home_card.dart

Closes #1635
Fix translation bug in homepage and academic path.
-   [X] Terms and conditions reflect the current change
-   [X] If aimed at production, writes a new summary in `whatsnew/whatsnew-pt-PT`
-   [X] Properly adds an entry in `changelog.md` with the change
-   [X] If PR includes UI updates/additions, its description has screenshots
-   [X] Behavior is as expected
-   [X] Clean, well-structured code

fix homepage translation bug

---

flake.lock
flake.nix

:sweat_smile:
The main changes are in the lockfile, which bumps https://github.com/limwa/nix-registry.
[Diff](https://github.com/limwa/nix-registry/compare/31195a80ba481162883a2097f6cac8cadfa2b13b...a1b4854927bd0fea198acd91013d22525dd419eb)

fix(nix): properly enable hardware acceleration
