NIAEFEUP/uni

app_feup/lib/redux/actionCreators.dart

Modified 'getUserExams' to only save exams from the curricular units the user belongs to.
Fix #27

Parsing exams by user UCs

---

app_feup/android/local.properties
app_feup/lib/controller/LoadInfo.dart
app_feup/lib/redux/ActionCreators.dart
app_feup/lib/view/Widgets/ExamCard.dart
app_feup/lib/view/Widgets/GenericCard.dart
app_feup/lib/view/Widgets/ScheduleCard.dart

The loading spinner should not appear if the information is already available locally
Fixes #146

Fixing loading spinner behavior in cards

---

app_feup/lib/view/Widgets/BugReportForm.dart

Fixed bug where the form became stuck after trying to submit a report and there was a problem with the github token.

Bug Report Form locking after error

---

app_feup/lib/redux/ActionCreators.dart

When logging in for the first time and checking the persistent login box, it was trying to load the locally stored information, even though it did not exist. This leaded to a null userInfo and, consequently, empty exams and an error in the profile page.

Fixed profile concurrency on first persistent login

---

app_feup/android/app/src/main/res/drawable/launch_background.xml
app_feup/android/app/src/main/res/values/styles.xml

It also fixes the fullscreen option given to the splash screen which was also causing the content to be in fullscreen.
This is what the splash screen looked like on a device.

Fixed small splash screen on certain screens

---

app_feup/lib/redux/action_creators.dart
app_feup/pubspec.yaml

Before the changes in this pull request were made, the exam entries would be sorted by exam type (I think). Now, with these changes, the exam entries in the exams page will be ordered by date.
The places where the exams need sorting are:
1. When the exams are scraped from the web (since this triggers an UI update).
2. ~~When the database is queried. In this case, I still called sort() in the code, instead of using sortBy in the database query, because it is easier to do it this way. Nonetheless, I am open to discussion on what is the best solution for this case.~~
**Before**
**After**

fix(exams): 🐛 sort exams by date

---

app_feup/lib/view/Pages/login_page_view.dart

Closes #221, closes #216 
Relevant changes:
- Keyboard loses focus on tapping the send button so that the toast is visible
- Text fields are now aligned left (were a bit weird centered with the eye icon)
- User number input spawns numerical keyboard instead of the complete one
- Password input field obscurity may be toggled with a switch
- Password input keyboard now has suggestions and auto correction disabled

Improve user login experience

---

app_feup/lib/model/entities/exam.dart
app_feup/lib/view/Widgets/exam_card.dart
app_feup/lib/view/Widgets/row_container.dart
app_feup/pubspec.yaml

Closes #315 
Tags exams from different exam periods:
- white color, for normal exams and minitests
- grey color, for extraordinary evaluation (resit exams, special ones, ...)

Exam color tagging

---

app_feup/lib/view/Widgets/bus_stop_search.dart
app_feup/pubspec.yaml

Closes #239
Very simple fix, building results for a certain query was returning an empty container when closing the search bar, now returns the suggestion list using the value of 'query'.

Empty bus stop list

---

app_feup/lib/controller/parsers/parser_schedule.dart
app_feup/lib/model/entities/lecture.dart
app_feup/lib/redux/action_creators.dart
app_feup/pubspec.yaml

Closes #336 
Switch back schedule api. Using html parser if schedule api is down or returns empty (as it did before)

Switch back schedule api

---

app_feup/lib/view/Widgets/bug_report_form.dart
app_feup/pubspec.yaml
app_feup/test/unit/view/Widgets/schedule_slot_test.dart

Closes #353
Switch to authorization header token access, because the old access method via url query was deprecated.

Switch to authorization header token access

---

app_feup/lib/view/Pages/general_page_view.dart

Closes #207 
Added a condition in buildAppBar function of GeneralPageView so that, when pressing the NI logo, only a new context is pushed to the navigator if the current page is not the main page.

Fixed repeated animation in the main page

---

app_feup/lib/controller/exam.dart
app_feup/lib/view/Pages/exams_page_view.dart
app_feup/lib/view/Widgets/exam_card.dart
app_feup/pubspec.yaml

Closes #344
As in the main page, in the exam section, there is a color tag for the different kinds of exams, it was applied the same method to the exams in **exams page**. Here are some screenshots of how both pages look.
**Main Page**
**Exams Page**

Adding color tagging feature in Exams Page

---

app_feup/README.md
app_feup/android/app/build.gradle
app_feup/pubspec.yaml

Closes #359 
Fixes semantic versioning sets target android SDK to 29, fixes `main.dart` file path in `README.md`

Small Release/Docs Fixes

---

app_feup/lib/controller/local_storage/image_offline_storage.dart
app_feup/lib/controller/logout.dart
app_feup/pubspec.yaml

`flutter_cache_manager` is now exposing the `File` API from the [file package](https://github.com/google/file.dart), which enters in direct conflict with `dart:io`'s `File`'s API. This PR fixes that error by only exposing the cache manager from `flutter_cache_manager`. 
More information on it can be found here: https://github.com/Baseflow/flutter_cache_manager/issues/320
This PR will fix the issues in #346

Fix flutter cache manager exporting File API

---

app_feup/lib/controller/local_storage/app_lectures_database.dart
app_feup/lib/controller/parsers/parser_schedule.dart
app_feup/lib/controller/parsers/parser_schedule_html.dart
app_feup/lib/model/entities/lecture.dart
app_feup/test/unit/redux/schedule_action_creators_test.dart
app_feup/test/unit/view/Pages/schedule_page_view_test.dart
app_feup/test/unit/view/Widgets/schedule_slot_test.dart
changelog.md

Closes #354 and eventually #355 .
There are two different constructors for lectures and they were inconsistent on how they handled schedules.

Fix lecture constructor

---

app_feup/android/app/build.gradle
app_feup/test/integration/src/schedule_page_test.dart
changelog.md

Any new update made to google play store is now required to have the target SDK version for Android 11 (level 30)
Updated `build.gradle`'s `targetSdkVersion` property

Update target SDK version to 30

---

app_feup/lib/controller/parsers/parser_exams.dart
app_feup/lib/model/entities/exam.dart
app_feup/lib/redux/action_creators.dart
app_feup/pubspec.yaml
app_feup/test/unit/redux/exam_action_creators_test.dart
changelog.md

Closes #371 
Avoids any duplicated exams due parsing errors.

Remove duplicated exams from parser

---

app_feup/lib/view/Widgets/bug_report_form.dart
changelog.md

Headers in order to post issue in github have changed, this PR fixes that.

Fix new header for github issues

---

app_feup/lib/view/theme.dart
app_feup/pubspec.yaml
changelog.md

Closes #329 
Changed the default checkbox color to dark red.

Changed the default checkbox color to dark red

---

app_feup/lib/model/entities/lecture.dart
app_feup/lib/view/Pages/schedule_page_view.dart
app_feup/lib/view/Widgets/request_dependent_widget_builder.dart
app_feup/pubspec.yaml
app_feup/test/integration/resources/schedule_example.json
app_feup/test/integration/src/schedule_page_test.dart
app_feup/test/unit/view/Widgets/schedule_slot_test.dart
changelog.md

Closes #367 
Tests were not adapted to the fact that we had the means to retrieve the data from two different fetchers and needed to be adapted.

Fix tests for the different schedule fetchers

---

app_feup/lib/controller/bus_stops/departures_fetcher.dart
app_feup/lib/controller/networking/network_router.dart
app_feup/pubspec.yaml
changelog.md

Closes #382 
The API now requires a CSRF token that we are able to obtain from the website itself. Introduced that in order to fix the bus stops

Get CSRF token for bus stops departures

---

uni/android/app/src/main/AndroidManifest.xml
uni/ios/Runner/Info.plist

The canLaunchUrl function was returning false in cases that aren't supposed. This happened because of an update of newer android versions.
To fixed it I added some <intend> tags to the <queries> at AndroidManifest.xml. And it works!
For IOS I also done the equivalent thing but didn't test.
[Android info](https://pub.dev/packages/url_launcher#android)
[IOS info](https://pub.dev/packages/url_launcher#ios)
@franciscopana This fix the canLaunchUrl function, can you check if this also close the #519?

Fix canLaunchUrl()

---

uni/lib/view/Widgets/create_print_mb_dialog.dart

Adds a paragraph to help students to know where the generated mb reference will be displayed.
-   [X] Terms and conditions reflect the current change
-   [X] Contains enough appropriate tests
-   [X] If aimed at production, writes new summary in `whatsnew/whatsnew-pt-PT`
-   [X] Properly adds entry in `changelog.md` with the change
-   [X] If PR includes UI updates/additions, its description has screenshots
-   [X] Behavior is as expected
-   [X] Clean, well structured code

Informating users where the reference is located

---

uni/lib/main.dart
uni/lib/model/app_state.dart
uni/lib/utils/constants.dart
uni/lib/utils/drawer_items.dart
uni/lib/utils/favorite_widget_type.dart
uni/lib/view/common_widgets/pages_layouts/general/general.dart
uni/lib/view/common_widgets/pages_layouts/general/widgets/navigation_drawer.dart
uni/lib/view/course_units/course_units.dart
uni/lib/view/home/widgets/bus_stop_card.dart
uni/lib/view/home/widgets/exam_card.dart
uni/lib/view/home/widgets/main_cards_list.dart
uni/lib/view/home/widgets/schedule_card.dart
uni/lib/view/login/login.dart
uni/lib/view/navigation_service.dart
uni/lib/view/schedule/schedule.dart

Closes #489 
This refactor hides content that should not be present when visiting the app from a university other than FEUP. 
The changes are not hardcoded so it's easy to make any more changes, simply alter the DrawerItem enum to change the visibility.

Hide information visibility according to faculties

---

uni/lib/model/entities/exam.dart
uni/lib/view/exams/widgets/exam_filter_menu.dart
uni/test/integration/src/exams_page_test.dart

Closes #599
The exam filter modal icon is now a funnel icon. The options "Port.Est.Especiais" and "Exames ao abrigo de estatutos especiais" were removed from the modal.

Change exam filter modal

---

uni/lib/controller/logout.dart
uni/lib/controller/networking/network_router.dart

Closes #624
Kills the Sigarra authentication when user logs out

Kill Sigarra auth session

---

uni/lib/view/profile/widgets/reference_card.dart

Closes #460
You can now see your references on the app (located in the 'Conta Corrente' card in the profile page).

Scrap MB references from Sigarra

---

uni/lib/view/library/library.dart

Do not hide whole library page when there is no data

---

uni/lib/controller/parsers/parser_library_occupation.dart
uni/lib/view/library/widgets/library_occupation_card.dart

Fixed fetching for empty library occupation. Max occupation will now be presented even if the library is empty. 
Also changed the background color because it did not generate a good contrast in the dark theme.

Fixed empty max seats for unavailable library data

---

uni/lib/view/locations/widgets/map.dart

Closes #694 
Also, added an attribution link required by the tile server service as shown below
<div>
</div>
-   [x] Clean, well structured code

Maps caching

---

uni/android/app/build.gradle

Needed to support some of the plugins we're using. 
With this change, we will drop support for Android versions older than 4.4.
Closes #821 

bump/bump and lock minimum Android SDK version

---

uni/lib/controller/background_workers/notifications/tuition_notification.dart
uni/lib/controller/local_storage/app_user_database.dart
uni/lib/controller/parsers/parser_fees.dart
uni/lib/model/entities/profile.dart
uni/lib/model/providers/profile_state_provider.dart
uni/lib/view/profile/widgets/account_info_card.dart

Closes #817 
Fixes bug when there are no more tuitions to pay and causes the worker to be rescheduled and be ran more often.

Fix exception when there are no more tuitions to pay

---

uni/lib/model/providers/startup/session_provider.dart
uni/lib/view/home/widgets/main_cards_list.dart

Fix card adders popup

---

uni/lib/controller/networking/network_router.dart

There was an issue with the relogin logic, that breaks almost every fetcher that depends on the student number on the app. 
When the user login info is saved, the username is saved as `upxxxxxxxxx` being `x` digits. When the app loads, it loads a fake session on `SessionProvider.restoreSession()` with username being the one loaded from user preferences (so therefore it loads `upxxxxxxxxx`) , when `NetworkRouter.getWithCookies` is called for the first time, it will try to do the request but it will know that this session is not valid (because on app start, it will have no cookies) and try to relogin. The cookies are copied from the newSession to the session that was given as an argument. The problem is that, the username stays the same so in the `upxxxxxxxxx` form, and every api to sigarra …

Fix relogin logic

---

.github/workflows/app_version_integrity.yaml
.github/workflows/format_lint_test.yaml
README.md

Closes #896 
This makes `format_lint_test` GH action run on `develop` and `master`, with the following tradeoffs:
- pro: status badge always point to stable branch; broken PRs no longer break it
- pro: safeguard in case of admin force push mistake
- pro: allows test coverage to be on the default branch after #898 
- con: some more minutes spent; we never had problems with it

Make build run on dev and master pushes

---

uni/pubspec.yaml

Closes #914 
This was causing `package_info_plus` to be downgrading to a old version (`2.0` and the current one is `4.0`) and crashing `flutter run` on newer versions of flutter (I'm using `3.10.6`). I need someone to test on the current version of flutter used by the project (`3.7`) to see if there aren't any regressions. 

Update sentry version

---

uni/lib/view/login/login.dart

Fix theme issues on login page

---

uni/lib/view/useful_info/widgets/other_links_card.dart

Add 'Consultas SASUP' to Useful links and hide prints link under "Úteis" tab

---

uni/android/app/build.gradle

Bumps target version to comply with Google's policy.

Update target sdk version

---

uni/lib/controller/parsers/parser_course_units.dart

Fix status parsing of multiple year UCs

---

uni/lib/controller/background_workers/notifications.dart
uni/lib/controller/local_storage/app_shared_preferences.dart
uni/lib/controller/networking/network_router.dart
uni/lib/main.dart
uni/lib/model/providers/lazy/exam_provider.dart
uni/lib/model/providers/lazy/lecture_provider.dart
uni/lib/model/providers/startup/profile_provider.dart
uni/lib/model/providers/startup/session_provider.dart
uni/lib/view/common_widgets/page_transition.dart
uni/lib/view/login/login.dart
uni/lib/view/terms_and_condition_dialog.dart
uni/pubspec.yaml
uni/test/integration/src/exams_page_test.dart
uni/test/integration/src/schedule_page_test.dart
uni/test/unit/providers/exams_provider_test.dart
uni/test/unit/providers/lecture_provider_test.dart

Fix user password encryption

---

.github/workflows/deploy.yaml
uni/lib/controller/fetchers/schedule_fetcher/schedule_fetcher_html.dart
uni/lib/controller/parsers/parser_schedule_html.dart
uni/lib/model/entities/lecture.dart
uni/lib/model/providers/lazy/lecture_provider.dart

The overlapping lectures are not completely fixed, because the desired behavior will require a more deep refactor. Now if a overlapping lectures is from a group of classes, the end time will be equal do the start time. I'll create a issue for a more in-depth refactor

Fix overlapping classes bugs

---

uni/lib/controller/fetchers/schedule_fetcher/schedule_fetcher_html.dart

This PR fixes an issue with the schedule HTML parser where the parser would only parse the classes from the first course of each student.

fix: schedule html parser not parsing all courses

---

uni/lib/controller/fetchers/course_units_fetcher/all_course_units_fetcher.dart
uni/lib/controller/parsers/parser_course_units.dart
uni/lib/model/providers/lazy/exam_provider.dart
uni/lib/model/providers/startup/profile_provider.dart
uni/lib/view/home/widgets/exam_card.dart

This PR fixes the problem where exams won't show up for students.
Firstly, an issue was fixed with the course unit parsing where the abbreviations of the course units were not parsed (the code was used instead).
Furthermore, this also fixed an issue with the exam filter not being saved properly.
Lastly, this also fixed an issue with the exam card where the weekday and month functions were not being called.

fix: exams not showing up

---

.github/workflows/deploy.yaml

Fix force push to develop on master hotfixes

---

uni/.gitignore
uni/ios/Podfile
uni/ios/Runner.xcodeproj/project.pbxproj
uni/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
uni/pubspec.lock
uni/pubspec.yaml

We had to bump the `add_2_calendar` version to `2.2.4` because of changes in swift. 
We also stage the podfile to ease the build of the project, we don't stage the podlock because dependencies are tracked by flutter. In order to the build process to work properly we had to create a `RunnerTests` target, since the podfile requires it.

Fixing ios build

---

uni/ios/Podfile
uni/ios/Runner.xcodeproj/project.pbxproj
uni/ios/Runner/Info.plist
uni/pubspec.lock
uni/pubspec.yaml

Closes #1011
Minimum ios deployment target bump and also connectivity_plus package due to an error associated with xcode 15.

Bump minimum ios version and connectivity_plus

---

uni/lib/model/entities/exam.dart

This PR changes the weekday selection logic to show the correct weekday for an exam.
The internationalization library we are using returns a list of weekdays from Sunday through Saturday. The weekday property on DateTimes returns a number from 1 (Monday) through 7 (Sunday). This means that `weekday % 7` must be used instead of `weekday - 1`. 

fix: show correct weekday in exams

---

uni/lib/controller/local_storage/app_exams_database.dart

Closes #996 
Removes `months` variable, which was not used.

Unused months removal

---

uni/lib/controller/networking/url_launcher.dart
uni/lib/generated/intl/messages_en.dart
uni/lib/generated/intl/messages_pt_PT.dart
uni/lib/generated/l10n.dart
uni/lib/l10n/intl_en.arb
uni/lib/l10n/intl_pt_PT.arb
uni/lib/view/about/widgets/terms_and_conditions.dart
uni/lib/view/schedule/widgets/schedule_slot.dart
uni/lib/view/terms_and_condition_dialog.dart
uni/lib/view/useful_info/widgets/link_button.dart
uni/lib/view/useful_info/widgets/text_components.dart

Closes #544 
Method that checks if the user's device can open a link (canLaunchUrl) and displays an toastMessage error if it can't.

Encapsulate Url Launch with Toast

---

uni/pubspec.lock
uni/pubspec.yaml

Closes #1016 
Add2calendar version bump due to a bug in iOS 17.

Exam add to calendar button fix

---

uni/lib/controller/parsers/parser_course_units.dart

This pull request handles nullable curricular years without throwing exceptions.
I'm not able to test this PR.

fix: handle nullable curricular years

---

uni/lib/generated/intl/messages_en.dart
uni/lib/generated/intl/messages_pt_PT.dart
uni/lib/generated/l10n.dart
uni/lib/l10n/intl_en.arb
uni/lib/l10n/intl_pt_PT.arb
uni/lib/view/restaurant/widgets/restaurant_page_card.dart

Closes #1000 
When a restaurant is favorited for the first time, it is asked if the user want to set the Restaurant Card in the Home Page.

Implement Restaurant Home Card Dialog

---

uni/lib/view/schedule/widgets/schedule_slot.dart

This PR fixes the class widget to show multiple rooms, if it has multiple rooms. Previously, all rooms after the first were not being shown.

fix: display multiple rooms

---

.github/dependabot.yaml

Makes Dependabot less annoying by making it ignore patch updates.

Make dependabot ignore patch updates

---

uni/.gitignore
uni/lib/view/common_widgets/pages_layouts/general/general.dart
uni/lib/view/common_widgets/pages_layouts/general/widgets/profile_button.dart

This PR prevents the users' profile image from being downloaded on every app navigation. It seems some legacy code was kept and it was preventing the cache mechanism from working properly.

fix: use cached profile image on navigation

---

uni/lib/controller/fetchers/exam_fetcher.dart
uni/lib/controller/parsers/parser_exams.dart
uni/lib/model/entities/exam.dart
uni/lib/view/exams/exams.dart
uni/lib/view/exams/widgets/exam_row.dart
uni/test/integration/resources/exam2_example.html
uni/test/integration/src/exams2_page_test.dart

Closes #800 
In Sigarra's exams page for FCUP and other faculties, some exams have their begin and end times in a different format, not previously supported by the Exams Parser. 

Fix Parser for different faculties 

---

.github/workflows/deploy.yaml
uni/assets/env/.env.example

Closes #1112.
This PR changes the CI to create the .env file that is bundled into uni.
To configure this env file, an env variable named UNI_ENV_FILE is used to set the file contents. Different environments for the main and develop branch may be used to distinguish between "beta" uni and "stable" uni.
I can't test this, so I call on @LuisDuarte1 to give his input on whether this would work.

ci: create env file for deployments

---

.github/workflows/deploy.yaml

This PR fixes an issue where variables from github environments can only be accessed through the vars context.

ci: fix missing var

---

uni/lib/controller/fetchers/calendar_fetcher_html.dart

Closes #1133.
This page changes the endpoint of the calendar to one that doesn't return a 403 error.

fix: use new endpoint for calendar

---

uni/lib/utils/navbar_items.dart
uni/lib/view/common_widgets/pages_layouts/general/widgets/bottom_navigation_bar.dart

Closes #1149 and closes #1147.
This PR adds tooltips to the navbar items and removes the splash animations.
https://github.com/NIAEFEUP/uni/assets/13498603/ae2a4ee5-3e38-4854-943d-6032dbb2911e
> [!NOTE]
> In the video, the tooltips appear when I hold my finger on the icons for about one second.

feat: add tooltips to navbar and remove splash effect

---

uni/lib/view/academic_path/academic_path.dart
uni/lib/view/common_widgets/page_title.dart
uni/lib/view/common_widgets/pages_layouts/general/general.dart
uni/lib/view/common_widgets/pages_layouts/general/widgets/top_navigation_bar.dart
uni/lib/view/common_widgets/pages_layouts/secondary/secondary.dart
uni/lib/view/faculty/faculty.dart
uni/lib/view/home/home.dart
uni/lib/view/home/widgets/main_cards_list.dart
uni/lib/view/home/widgets/uni_icon.dart
uni/lib/view/restaurant/restaurant_page_view.dart
uni/lib/view/transports/transports.dart

Closes #1146 
This PR adds titles to the general pages. It also fixes some appearance issues with the App Bar.
https://github.com/NIAEFEUP/uni/assets/13498603/98cecaaf-0d87-4ce3-87ec-6fdb7d7fab56
https://github.com/NIAEFEUP/uni/assets/13498603/19141195-80f1-464d-9f95-aff871c6bea2
- Method `getTitle` was added to general pages. This method returns the title string that is used in the UI. Localized strings are used to adapt to user's language setting.
- Page titles are not left aligned, unless center property is true (legacy behaviour)
- Profile button was also added to the app bar on the general page layout.
- Colors were adjusted in the app bar and shadows were added to it.
-   [x] If aimed …

feat: add titles to general pages

---

uni/lib/view/common_widgets/pages_layouts/general/general.dart
uni/lib/view/common_widgets/pages_layouts/general/widgets/profile_button.dart
uni/lib/view/common_widgets/pages_layouts/general/widgets/top_navigation_bar.dart
uni/lib/view/common_widgets/widgets/profile_image.dart
uni/lib/view/home/home.dart
uni/lib/view/profile/profile.dart
uni/lib/view/profile/widgets/profile_overview.dart

This PR fixes an issue with the profile button in the navbar.
The clipping occurred because the profile button had padding on the bottom, which made it move up and overflow.
I took this opportunity to extract a component called ProfileImage. Also, a CircleAvatar was used instead of a box decoration.
This also fixes a issue overlooked in the #1152 where the settings icon in the profile page had too much padding on the right.
https://github.com/NIAEFEUP/uni/assets/13498603/5b5f7f0d-4dda-4944-b322-d760301dcbe4
-   [x] If PR includes UI …

fix: profile button is no longer clipped on navbar

---

uni/lib/generated/intl/messages_all.dart
uni/lib/generated/intl/messages_en.dart
uni/lib/generated/intl/messages_pt_PT.dart
uni/lib/generated/l10n.dart
uni/lib/l10n/intl_en.arb
uni/lib/l10n/intl_pt_PT.arb
uni/lib/view/schedule/widgets/schedule_slot.dart
uni/test/test_widget.dart
uni/test/unit/view/Pages/exams_page_view_test.dart

Changing uc link to open in app page

---

uni/lib/generated/intl/messages_en.dart
uni/lib/generated/intl/messages_pt_PT.dart
uni/lib/generated/l10n.dart
uni/lib/l10n/intl_en.arb
uni/lib/l10n/intl_pt_PT.arb
uni/lib/view/schedule/schedule.dart
uni/test/unit/view/Pages/exams_page_view_test.dart

Closes #946.
Supersedes #1039.
In this PR, a tab for Saturday is added. Furthermore, a new translation for no classes on weekends is also added.

fix: add weekend schedule

---

uni/lib/main.dart

Closes #1174.
This PR changes the order of providers so that session provider is loaded before profile, exams and lectures providers.

hotfix: null state on providers first use

---

uni/lib/controller/networking/url_launcher.dart
uni/lib/view/locations/widgets/map.dart
uni/lib/view/login/login.dart

Fixes an issue where the future returned by `canLaunchUrl` was being cast to a bool. Also refactors every launchUrl to use launchUrlWithToast.

hotfix: launch url with toast

---

uni/lib/model/providers/plausible/plausible_provider.dart

This PR adds proper error handling code to PlausibleProvider to protect from situations where devices don't implement battery save mode capabilities. If a device doesn't implement them, we consider that the device never is in battery saving mode.

hotfix: proper error handling in plausible provider

---

uni/lib/controller/fetchers/departures_fetcher.dart

This PR changes the CSS selector used to retrieve the CSRF token in bus stops operations. 

hotfix: retrieve bus stops' csrf token

---

.github/workflows/deploy.yaml

This occurs when there are too many PRs merged in a 10-minute window. To avoid this, we set a concurrency group per branch (in this case only develop and master apply). I feel like canceling the previous deploy actions makes the merged PR less semantic because we technically lose track of where the hotfixes happened.

Fix concurrency issue on deploy action

---

uni/lib/model/providers/lazy/bus_stop_provider.dart

This PR fixes a `ConcurrentModificationError`.
Stacktrace:
```
ConcurrentModificationError: Concurrent modification during iteration: _Map len:0.
File "compact_hash.dart", line 714, in _CompactIterator.moveNext
File "bus_stop_provider.dart", line 30, in BusStopProvider.fetchUserBusTrips
File "<asynchronous suspension>"
File "bus_stop_provider.dart", line 62, in BusStopProvider.removeUserBusStop
```

hotfix: concurrent modification in bus stop provider

---

.github/workflows/deploy.yaml
.github/workflows/format_lint_test.yaml

[I contributed this feature to subosito/flutter-action](https://github.com/subosito/flutter-action/releases/tag/v2.15.0). Now we don't have to use a separate `yq` step :-)

CI: use `flutter-version-file` argument to subosito/flutter-action

---

uni/lib/model/utils/time/week.dart

This pull request makes the week util class handle timezone changes properly.
Dart's standard lib, when asked to add or subtract 7 days from a DateTime will, instead, add/subtract the equivalent of 7 days in seconds.
This results in wrong calculations when the week contains a timezone change. By copying the dates with `isUtc: true`, the calculations become correct, since UTC does not have timezone changes.

hotfix: make week handle timezone changes

---

uni/lib/main.dart
uni/lib/model/providers/plausible/plausible_provider.dart
uni/lib/view/profile/widgets/create_print_mb_dialog.dart
uni/pubspec.lock
uni/pubspec.yaml

Added user agent and screen width size to plausible

---

uni/android/app/proguard-rules.pro

After some investigation on #1242, I've concluded that:
- `javax.annotations` has annotations included in the [JSR305](https://jcp.org/en/jsr/detail?id=305), which is a spec of annotations that help with IDEs or other tools to avoid software defects.
- `com.google.errorprone` has annotations related to [ErrorProne](https://errorprone.info/bugpatterns), a static analyzer with its own set of annotations like above.
These annotations are not reflected at runtime in any shape or form so, it's safe to ignore them (unfortunately, libs cannot specify what to ignore or not on proguard, so we need to do this by hand).
This PR groups the two annotation packages.

Abstract proguard rules at package level

---

uni/android/app/proguard-rules.pro

For some reason `javax.annotation.concurrent` is not covered by `javax.annotation.*`

Update proguard-rules.pro to include concurrent annotations

---

uni/android/build.gradle
uni/pubspec.lock
uni/pubspec.yaml

Fixing deploy pipeline

---

packages/uni_app/lib/controller/local_storage/database/app_lectures_database.dart

Fixes an issue where schedule loading presents an error when the app is first opened.
This is because the loadFromStorage method throws an unexpected error.

fix: schedule loading from storage

---

packages/uni_app/lib/controller/fetchers/schedule_fetcher/schedule_fetcher_new_api.dart
packages/uni_app/lib/controller/parsers/schedule/new_api/parser.dart

When a student does not have their schedule yet, the page does not have the required tag to access the api url.

Fix schedule null api URL

---

packages/uni_app/lib/controller/local_storage/database/app_lectures_database.dart

Fixes an issue where the lectures are stored with NULL blocks.
When reading the lectures, an error is thrown when attempting to read the blocks field.

fix: lectures database serialization

---

packages/uni_app/lib/controller/fetchers/library_occupation_fetcher.dart

This PR fixes an issue where library information fetching fails when there is null progress. We assume that `null` means 0 in the affluences API.

fix: error when null progress in library

---

packages/uni_app/lib/controller/parsers/parser_course_unit_info.dart

This PR fixes an issue where fetching a curricular unit's details fails when there is no bibliography on SIGARRA for the unit.

fix: error when there is no unit bibliography

---

packages/uni_app/lib/controller/fetchers/schedule_fetcher/schedule_fetcher.dart
packages/uni_app/lib/controller/fetchers/schedule_fetcher/schedule_fetcher_api.dart
packages/uni_app/lib/controller/fetchers/schedule_fetcher/schedule_fetcher_new_api.dart
packages/uni_app/lib/model/providers/lazy/lecture_provider.dart

Removes all profile references from the lecture provider because it is no longer needed.

refactor: remove profile from lecture provider

---

packages/uni_app/lib/model/providers/state_provider_notifier.dart

Fixes an issue where entering the course unit info page after a login results in an error.
Good catch, @Process-ing.

fix: unit info error on relogin

---

packages/uni_app/lib/app_links/uni_app_links.dart
packages/uni_app/lib/controller/networking/network_router.dart
packages/uni_app/lib/utils/uri.dart

Fixes an issue where fetching the calendar returns no events due to a wrong URL, after conversion of %20 to + in Dart's standard lib.

fix: empty calendar

---

packages/uni_app/lib/view/bus_stop_next_arrivals/bus_stop_next_arrivals.dart
packages/uni_app/lib/view/exams/exams.dart

Fixes the backgrounds of exam widgets and transport tabs.
This was caused by previous changes to the theme of the app, made in 9caa64ecf9f1f500df691b0db3a46310073700b1.

fix: exams and transport backgrounds

---

packages/uni_app/pubspec.lock
packages/uni_app/pubspec.yaml
packages/uni_app/windows/flutter/generated_plugins.cmake

Due to an incompatibility in the sentry package, the IOS build was not succeding, therefore a bump was needed to a fixing version. More details below:
https://github.com/getsentry/sentry-dart/issues/2096
https://github.com/flutter/flutter/issues/151467

Fixing IOS build v1.9.3

---

packages/uni_app/lib/view/home/widgets/schedule_card.dart
packages/uni_app/lib/view/lazy_consumer.dart

Closes #1238 
1. Changed `LazyConsumer` to use a mapper function that, by default, returns the value itself.
2. Implemented a mapper function on `schedule_card` to filter out classes that have already ended.
Before this fix, if there were no more classes scheduled, but the student had a class that day (thus the schedule wasn't empty), the `schedule_card` did not show any content. Now, it shows "No classes to present":
| Before | After |
|--------|--------|
| ![Screenshot_2024-10-31-01-37-18-246_pt up fe ni uni](https://github.com/user-attachments/assets/f8e4b5e5-fdcf-493d-a651-09535e7106d3) | ![Screenshot_2024-10-31-01-31-28-409_pt up fe ni uni](https://github.com/user-attachments/assets/6773b7a7-5264-464b-9a62-d011a2e27f2c) |
To test, change the `lecture_provider` to return a list with a …

feat: added mapper function to LazyConsumer

---

packages/uni_app/lib/session/flows/credentials/request.dart
packages/uni_app/lib/session/flows/federated/request.dart
packages/uni_app/lib/sigarra/endpoint.dart
packages/uni_app/lib/sigarra/endpoints/api/authentication/authentication.dart
packages/uni_app/lib/sigarra/endpoints/api/authentication/login/login.dart
packages/uni_app/lib/sigarra/endpoints/api/authentication/login/response.dart
packages/uni_app/lib/sigarra/endpoints/html/authentication/authentication.dart
packages/uni_app/lib/sigarra/endpoints/html/authentication/login/login.dart
packages/uni_app/lib/sigarra/endpoints/html/authentication/login/response.dart
packages/uni_app/lib/sigarra/endpoints/html/authentication/logout/logout.dart
packages/uni_app/lib/sigarra/endpoints/oidc/oidc.dart
packages/uni_app/lib/sigarra/endpoints/oidc/token/response.dart
packages/uni_app/lib/sigarra/endpoints/oidc/token/token.dart
packages/uni_app/lib/sigarra/options.dart
packages/uni_app/lib/sigarra/response.dart

Refactors the endpoints to use inheritance. Useful to enforce a specific structure for all endpoints, as well as having functions that accept a generic `Endpoint<T>`.

refactor: use inheritance for endpoints

---

packages/uni_app/android/app/src/main/AndroidManifest.xml

This fixes an issue on Android where, after being reinstalled, the uni app will not open, until its data is cleared.
My current hypothesis is that this is happening because, upon reinstallation, the Android system restores the app files from a backup. This is causing some incompatibility with the secure shared preferences or something of sorts.

fix: app halting after installation

---

packages/uni_app/lib/controller/fetchers/course_units_fetcher/course_units_info_fetcher.dart
packages/uni_ui/lib/timeline/timeline.dart

Because my master includes courses from different faculties, I encountered trouble viewing courses from FCUP.  
The issue occurs in the `fetchSheet` function because we only check the first endpoint. 
To address this, I modified the code to traverse the endpoints and check for the presence of the `language` field in the response. This solution works but feels a bit clunky, if anyone has a better aproach, i'd   greatly appreciate your input. I had to check for the field `language` because even when querying the wrong endpoint, we still receive a success response.   
<div align="center">
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/77e1c8ed-2967-40cf-9ddc-72e4d286be54" alt="Before" height="600px"></td> …

Update fetchSheet to work with multiple endpoints

---

packages/uni_app/lib/view/common_widgets/pages_layouts/general/general.dart
packages/uni_ui/lib/navbar/bottom_navbar_item.dart

This PR fixes the problems we had with the bottom navigation bar.
<p align="center">
</p>
Problems fixed:
- Background behind bottom navbar not being transparent
- Bottom navbar icons being too small
- Bottom navbar buttons being misaligned with the center of the navbar

Fix Bottom Navbar

---

packages/uni_app/lib/controller/fetchers/book_fetcher.dart
packages/uni_app/lib/view/course_unit_info/widgets/course_unit_sheet.dart

Closes #[1436]
Added a second API openLibrary to the book fetcher. 
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/c557ae06-0c3f-47c7-bf4e-53cf792e6732" alt="Screenshot 2" width="400"></td>
<td><img src="https://github.com/user-attachments/assets/01154a36-859d-45e2-8345-9129bfeccd2b" alt="Screenshot 1" width="400"></td>
</tr>
</table>

Added openLibrary API

---

packages/uni_app/lib/main.dart

A potential fix for the navigation bar overlapping content. It's an idea. I disabled the transparency (it is now black), so the app content appears above it.

Fix for the navigation bar appearing above content.

---

packages/uni_ui/lib/cards/library_occupation_card.dart

Closes #1474
Fixes the issue regarding the weird size/shape of the library card when inserted at the home and faculty pages.
<div>
</div>

fix: Library card size

---

packages/uni_app/lib/view/academic_path/exam_page.dart
packages/uni_app/lib/view/restaurant/widgets/day_of_week_tab.dart
packages/uni_app/lib/view/restaurant/widgets/days_of_week_tab_bar.dart

Closes #1492 
I think it is done, given the differences in how the pages were constructed the exact values of paddings and sizes are different, but visually I think they are almost indistinguishable now. 
In another note, shouldn't the restaurant page's week be starting from Sunday?

Uniformize all timelines padding and width

---

packages/uni_app/lib/view/academic_path/courses_page.dart

Closes #1491 
Applied padding only on left, right and bottom.
Before            |  After
:----------------:|:-------------------------:

Fix: course page top blank padding

---

packages/uni_app/lib/view/restaurant/widgets/days_of_week_tab_bar.dart

Closes #1488 
Added an overlayColor to the days_of_week_bar_tab widget to correct the restaurant's timeline background.
https://github.com/user-attachments/assets/1b639af5-cf5f-4d9a-9058-024a23e2a835
https://github.com/user-attachments/assets/d266c7e4-2167-4666-9ec2-e1f39c9f8950

Fix: restaurant's timeline background

---

packages/uni_ui/lib/cards/generic_card.dart

Closes #1489 
Fixed the bug, reorder the gesture detector in the GenericCard widget.

Fixed clickable area that was only on the text in the GenericCard

---

packages/uni_ui/lib/courses/course_card.dart
packages/uni_ui/lib/theme.dart

Closes #1490 
before:
after:
to-dos

Fix course card color and width

---

packages/uni_app/lib/generated/intl/messages_en.dart
packages/uni_app/lib/generated/intl/messages_pt_PT.dart
packages/uni_app/lib/generated/l10n.dart
packages/uni_app/lib/l10n/intl_en.arb
packages/uni_app/lib/l10n/intl_pt_PT.arb
packages/uni_app/lib/view/academic_path/courses_page.dart
packages/uni_app/lib/view/academic_path/widgets/course_units_view.dart
packages/uni_ui/lib/courses/average_bar.dart
packages/uni_ui/lib/courses/course_card.dart
packages/uni_ui/lib/courses/course_info.dart
packages/uni_ui/lib/courses/course_selection.dart

Closes #1504. The problem occurs because some courses have only one curricular unit associated with no ECTS, failing in some NaNs (due to divisions by zero) and null checks.
<p align="center">
</p>
- Added checks to handle cases where the UCs do not have ECTS, along with the whole course in the average bar
- Improved some info displayed on such cases (average)
- Added translations to "now" text
-   [X] If PR includes UI updates/additions, its description has screenshots
-   [X] Behavior is as expected
-   [X] Clean, well-structured code

Fix courses page for courses with no ECTS

---

packages/uni_app/lib/view/home/home.dart

Closes #1544 
Now the `postFrameCallback` only causes a rebuild if the state actually changes.
Even without moving the screen it is constantly re-building and re-rendering!
It only re-builds and re-renders when interacted with (as it should).

Fix infinite home page rebuild

---

packages/uni_app/lib/generated/intl/messages_en.dart
packages/uni_app/lib/generated/intl/messages_pt_PT.dart
packages/uni_app/lib/generated/l10n.dart
packages/uni_app/lib/l10n/intl_en.arb
packages/uni_app/lib/l10n/intl_pt_PT.arb
packages/uni_app/lib/view/home/widgets/tracking_banner.dart

Changed the text in the statistics banner, to avoid using the "We now". 
Also added more top-margin to avoid the overflow between the banner and the edit button
<div align="center">
</div>

Changed the text in the statistic's banner

---

packages/uni_app/ios/Runner/Info.plist

Closes #1597 
reverted `Info.plist` to its old version so the app launches on iOS

fix: make app run in iOS

---

packages/uni_app/lib/controller/background_workers/notifications.dart

When running in debug mode and the app was not installed on the device, this error would popup every now and then. It is now fixed.

Fixed error in android notification permission request
